# Константы для работы бота
(
    CHOOSING_OPTIONS, SELECTING_ACTION, INPUT_TIME_CODE,    # states
    SELECTING_SONG, TYPING_SONG_NAME, RESTART_SEARCH,
    TRACK_ID, TRACK_FILE_PATH, FILE_DURATION,               # user_data
    DURATION_LEFT_BORDER, DURATION_RIGHT_BORDER,
    DURATION_START, DURATION_CUSTOM, SET_TIME_CODE,         # callback_queries
    BACK_TO_MENU, CREATE_VIDEO_MESSAGE
) = map(chr, range(16))
